export const robertBio = 'Robert discovered a love for music at age 9 when he first picked up his grandfather’s alto saxophone. He went on to develop a talent for singing, became trained in classical voice, and performed professionally in the Sacramento area, including appearances with the Sacramento Philharmonic and the Sacramento Opera Company. He attended Natomas Performing & Fine Arts Academy and gained experience as a music and vocal director for local theater companies, including Woodland Opera House and Runaway Stage Productions. He also enjoys performing on stage, and most recently appeared as “The Gardener” in Michael McLean’s musical oratorio “The Garden” and as a member of the Grand Chorus in Millennial Choirs & Orchestras prodution of "Messiah in America".'

export const robertBio2 = 'After serving in the U.S. Air Force for six years, Robert obtained a Bachelor’s degree in Psychology with an emphasis in Applied Behavior Analysis and has enjoyed working with children with special needs over the last several years. He has taught music for the last five years and is curently pursuing his NTMA certification in Vocal Teaching. He is a proud dad of four and in his spare time enjoys coding software, spending time with his family, and learning to tune and repair instruments.'

export const ericaBio = 'Erica has been teaching piano for over twenty years and is a member of the Treasure Valley Music Teachers Association. She began piano lessons at the age of 6 and dedicated her growing-up years to performing and competing throughout Northern California. She obtained an Associates Degree in Music with a Certificate in Music History & Literature at Foothill College, and continued her musical studies while pursuing a bachelor’s degree in Human Development at BYU-Provo. She enjoys performing on stage (especially with her husband), and has also served as a music director, vocal director, and accompanist, and plays professionally for private and public events. When she’s not busy with music or homeschooling her four children, she enjoys composing her own music, reading, writing, and running half-marathons.'

export const philosophy1 = 'We believe in the power of music to change the course of lives. Having both been introduced to musical studies at a young age, we have personally experienced the  tremendous positive effects that music had on our personal development and continues to have in our lives. We have seen this with our own children and our students, and there are few things more exciting than witnessing young people discover a deep love for and understanding of music.'

export const philosophy2 = 'We believe that every person has musical ability, no matter their age, and that our job as teachers is to help students recognize and expand their innate capabilities and strengths. We believe that a strong foundation in music theory is essential for continued growth in musical skill and appreciation. Like learning to read words in books, learning to read musical notation on the printed page opens up a world of possibilities. We also strive to develop our students’ ears, and to hone their sensitivity to the nuance of musical pitch, tempo, rhythm, and style.'

export const philosophy3 = 'We also emphasize the importance of being able to perform in front of an audience. Not only does this allow students to share their musical talent and the pieces they personally love, but it also develops confidence and poise that translates into other areas of life. '